### Register 
POST http://localhost:5000/api/user/register
Content-Type: application/json

{
    "firstName": "Thu",
    "lastName": "Nguyen",
    "username": "jokertn16",
    "password": "123",
    "email": "jokertn16@gmail.com"
}

### Login 
POST http://localhost:5000/api/user/login
Content-Type: application/json

{
    "username": "jokertn16",
    "password": "123"
}

### Profile
GET http://localhost:5000/api/user/profile/tommy087

### Update Profile
PUT http://localhost:5000/api/user/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxhcHRyaW5odmllbiIsImlkIjoiNjM0ZTY2MjlkZTAxNTNmYTBlYTA1OTY5IiwiaWF0IjoxNjY2MTAxNzczLCJleHAiOjE2NjY1MzM3NzN9.htqinxC4FuDCXQ2b3wiKr5l13ItXgov87MWNP9IaQJg

{
    "info.bio": "No description, website, or topics provided.",
    "setting.isPrivateAccount": true,
    "firstName": "Post",
    "lastName": "Malone"
}

### Following user
PUT http://localhost:5000/api/user/follow
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Impva2VydG4xNiIsImlkIjoiNjM0ZWMyOTRkOTg1ODRmN2YxNmY2ZjZmIiwiaWF0IjoxNjY2MTA4MjEwLCJleHAiOjE2NjY1NDAyMTB9.AV-zCSK6L_FesYo5pGTuYtMiyholHJIDaDRjY4_QJWE

{
    "followId": "634ec294d98584f7f16f6f6f"
}

### User's Followers 
GET http://localhost:5000/api/user/followers/tommy087

### User's Following 
GET http://localhost:5000/api/user/following/tommy087

