### Register 
POST http://localhost:5000/api/user/register
Content-Type: application/json

{
    "firstName": "Krix",
    "lastName": "Daniel",
    "username": "laptrinhvien",
    "password": "123",
    "email": "ltv.aptech2019@gmail.com"
}

### Login 
POST http://localhost:5000/api/user/login
Content-Type: application/json

{
    "username": "laptrinhvien",
    "password": "123"
}

### Profile
GET http://localhost:5000/api/user/profile/tommy087
