### Create section
POST http://localhost:5000/api/section
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxhcHRyaW5odmllbiIsImlkIjoiNjM0ZTY2MjlkZTAxNTNmYTBlYTA1OTY5IiwiaWF0IjoxNjY3OTc4Nzc0LCJleHAiOjE2Njg0MTA3NzR9.dqK3p9sYf4-ThowlkX8MY-JR6h5rtISkTt_k_HkbUZE
Content-Type: application/json

{
    "boardId": "636b62fab047ebc3a328df55"
}

### Update section
PUT http://localhost:5000/api/section/636bab2ae0bd47e7c22fa274
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxhcHRyaW5odmllbiIsImlkIjoiNjM0ZTY2MjlkZTAxNTNmYTBlYTA1OTY5IiwiaWF0IjoxNjY3OTc4Nzc0LCJleHAiOjE2Njg0MTA3NzR9.dqK3p9sYf4-ThowlkX8MY-JR6h5rtISkTt_k_HkbUZE
Content-Type: application/json

{
    "title": "OK",
    "icon": "💔"
}


### Delete section 
DELETE http://localhost:5000/api/section/636bab2ae0bd47e7c22fa274
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxhcHRyaW5odmllbiIsImlkIjoiNjM0ZTY2MjlkZTAxNTNmYTBlYTA1OTY5IiwiaWF0IjoxNjY3OTc4Nzc0LCJleHAiOjE2Njg0MTA3NzR9.dqK3p9sYf4-ThowlkX8MY-JR6h5rtISkTt_k_HkbUZE